### PR TITLE
Make more like figureW depleteSynergy

### PR DESCRIPTION
**Pull request by stephendl102**

### CODE REVIEW

**Comment by aarmey** [comment]
@stephendl102 check the output on Jenkins to make sure this looks like what you expect. Otherwise this should be ready to merge. There were just a couple unmatched parentheses.

**Comment by aarmey** [comment]
@stephendl102 where's this at? Something I can help with?

**Comment by stephendl102** [comment]
Screen Shot 2020-03-22 at 12 05 08 AM
It's all ready to go. For some reason, plotIsobologram did not like having L0 and f passed into it, but it doesn't really matter because these two functions have hardcoded aspects, so it won't be part of the general function that Cyrillus wrote anyway. Also, subfigure 5 and 6 are both the same because I wasn't sure how to implement an empty subfigure. I am not able to run make figureB1.svg so I can't see if it builds before checking Jenkins after a pull request. Anyway, everything is at least correct and functional. @aarmey

**Comment by aarmey** [comment]
Great. Will merge. Think I fixed that permissions problem.

**Pull request merged**
