### PR TITLE
Error bar as quantile; makefile for humanized mice

### PR DESCRIPTION
**Pull request by cyrillustan**

### CODE REVIEW

**Comment by cyrillustan** [comment]
@aarmey the humanized figures are here

**Comment by cyrillustan** [comment]
Gonna merge it

**Comment by aarmey** [comment]
Great @cyrillustan, a few thoughts:

- I see what you mean about the noisy measurements. In particular, the noisy baseline is an issue, since it creates systematic error in how much of an effect each treatment has. Maybe handling the baseline cell number as an unknown is better?
- One of our central goals is to figure out how to use murine measurements to predict what happens in the human/humanized case. Perhaps you can fix the relative weighting of all the cell populations based on the murine equivalent? In other words, have a single scaling value that's multiplied by the murine parameters to give you the humanized cell weights.
- Have you tried looking at [humanized ITP](https://github.com/meyer-lab/FcgR.jl/blob/master/data/nimmerjahn-humanized-ITP.csv)? If nothing else these measurements should be much less noisy.

**Comment by cyrillustan** [comment]
@aarmey  I'm not sure that I get everything. What do you mean exactly by treating the baseline cell number as unknown?
I'll try to have only a single number to transform mice to humanized mice. Some issues will still exist though, but let's see how the result goes.
I'll import and perform regression on humanized ITP data. I need some explanations about various IgG1 variants (hIgG1-PBS, hIgG1-2.5g/kgIVIg, etc.).

**Comment by aarmey** [comment]
What I mean is the same as what you've referred to previously regarding depletion being a function of two measurements. Depletion comes from a measurement of baseline abundance, then a second measurement of abundance after treatment. The baseline has to be accurately estimated, since it influences predictions for all treatments.

I think you want to ignore the treatments with IVIG—that's serum given to compete with and inhibit the IgG. It's not very defined what it is. We can walk through the data in more detail on Monday, too.

**Comment by cyrillustan** [comment]
Okay, I'll try things out and talk about them on Monday

**Pull request merged**
