### PR TITLE
SynvFcrExpr

### PR DESCRIPTION
**Pull request by stephendl102**

### CODE REVIEW

**Comment by stephendl102** [comment]
There is a problem with the dot in "synergy = dot(weights, curve) / 2.0" within calcSynergy? @aarmey

**Comment by aarmey** [comment]
What sort of problem?

**Comment by stephendl102** [comment]
Nevermind, it was a build error that became fixed when master was merged into this branch. It is ready to merge now pending 1 approving review.

**Comment by stephendl102** [comment]
Sorry to bother again, but it says "The base branch restricts merging to authorized users"

**Comment by aarmey** [comment]
Hmm. I’ll just merge then.

**Pull request merged**
