### PR TITLE
L0 v search

### PR DESCRIPTION
**Pull request by cyrillustan**

### CODE REVIEW

**Comment by cyrillustan** [comment]
@robthemike1 you need to update your branch since it's very outdated. Gadfly works on my end, so see if these can run on your side.

**Comment by robthemike1** [comment]
I tried this on my end but now there is a regression problem. "type fitResult has no field minimum"

**Comment by aarmey** [comment]
@robthemike1 where's this at?

**Comment by robthemike1** [comment]
Build 17 worked, but it failed when I updated it from master. I just updated it again with the new changes and hopefully it should work

**Comment by robthemike1** [comment]
I couldn't get it to work for the humanized regression, but it is set for the murine cases

**Pull request merged**
